// ORGANIZATION
export const ORG_NAME_LOADING = 'ORG_NAME_LOADING';
export const ORG_NAME_LOADED = 'ORG_NAME_LOADED';

// PEOPLE
export const PEOPLE_LOADING = 'PEOPLE_LOADING';
export const PEOPLE_LOADED = 'PEOPLE_LOADED';
export const SET_PERSON = 'SET_PERSON';
export const SET_CITY = 'SET_CITY';

// SURVEY
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const QUESTIONS_LOADED = 'QUESTIONS_LOADED';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const DECISION_LOADED = 'DECISION_LOADED';
