// ORGANIZATION
export const ORG_NAME_LOADING = 'ORG_NAME_LOADING';
export const ORG_NAME_LOADED = 'ORG_NAME_LOADED';

// PEOPLE
export const PEOPLE_LOADING = 'PEOPLE_LOADING';
export const PEOPLE_LOADED = 'PEOPLE_LOADED';

// QUESTIONS
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const QUESTIONS_LOADED = 'QUESTIONS_LOADED';
